# profile for testing the workflow on slurm

# use slurm as executor
executor: slurm

# maximum number of jobs
jobs: 50

# use conda environments
use-conda: true

# rerun incomplete jobs
rerun-incomplete: true

# default resources for all rules
default-resources:
    mem_mb: 4000
    runtime: 360
    threads: 4

# specific resources for certain rules
set-resources:
    getorganelle:
        mem_mb: 64000
        runtime: 1440
        threads: 6
    blobtools_create:
        mem_mb: 10000
